services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.3
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 2181 || exit -1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.6.3
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy

  realtime-subscriber:
    build:
      context: ./realtime-subscriber/
      dockerfile: Dockerfile
    env_file:
      - realtime-subscriber/.env
    restart: unless-stopped
    depends_on:
      broker:
        condition: service_healthy
