services:
  transactions-service:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/transactions/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
